### ISSUE TITLE
Export using contextual menu for NIDM-Results 1.3.0

### ISSUE THREAD

**Issue by cmaumet** [incf-nidash/nidmresults-spm#31]
To be discussed with @gllmflndn: currently the exporter does not support export to NIDM-Results 1.3.0 via the contextual menu as additional arguments have to be entered by the user (number of subjects, group name, reference space, modality).

**Comment by cmaumet** [comment]
@gllmflndn: I forgot to discuss with you during the NIDM Hackathon last week. 

#30 broke the export through the contextual menu. How do you think we should handle this export? Shall we open a popup and ask the user for his input to fill up "number of subjects", "group name(s)",  "reference space" and "modality"?

**Comment by gllmflndn** [comment]
When used interactively (through the contextual menu), the user is now asked about the missing information:
https://github.com/incf-nidash/nidmresults-spm/pull/36
